name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt install -y gcc-12-arm-linux-gnueabi qemu-user

    - name: build neon_test1
      run: make neon_test1

    - name: build neon_test_select
      run: make neon_test_select

    - name: run neon_test1
      run: make run_neon_test1

    - name: run neon_test_select
      run: make run_neon_test_select

    - name: run asm
      run: make asm

    - name: diff
      run: diff neon_test_select_normal.s neon_test_select.s

    - uses: actions/upload-artifact@v4
      with:
        name: asm
        path: *.s
